#!/bin/bash

# ---------------------------------------------------------------------------- #
# GLOBAL VARIABLES (in script)                                                 #
# ---------------------------------------------------------------------------- #

CONFDIR="/opt/websitemanager"
DOMAIN=''
# red output
RED='\033[0;31m'
# green output
GREEN='\033[0;32m'
# Yellow outpu
YELLOW='\033[0;33m'
# No Color
NC='\033[0m'
POOL_TEMPLATE="/opt/websitemanager/phpini-templates/php-fpm.conf"
HAS_POOL_TEMPLATE="1"
USERNAME=""
mysqlcred="/opt/websitemanager/mysql"
domainslist="/opt/websitemanager/domainlist"
# ---------------------------------------------------------------------------- #
# FUNCTIONS                                                                    #
# ---------------------------------------------------------------------------- #

#
# Echoes a red message
#
echo-red() {
    echo -e "${RED}$1${NC}"
}

#
# Echoes a green message
#
echo-green() {
    echo -e "${GREEN}$1${NC}"
}

#
# Echoes a yellow message
#
echo-yellow() {
    echo -e "${YELLOW}$1${NC}"
}


#
# Shows info on the authors and the program
#
websitemanager-credits() {

    echo -e "${GREEN}"
    cat <<splash
##############################################################################
##############################################################################
# websitemanager v1.3.0 Created by LKY Rajpurohit <jodhpur.laxman@gmail.com> #
##############################################################################
##############################################################################

splash
    echo -e "${NC}"

}

#
# Verifies sudo 
#
websitemanager-verify-sudo() {

    if [ "$EUID" -ne 0 ]
      then echo-red "Please execute as root eg: sudo"
      echo-red "else contact server administrator"	    
      exit 1
    fi

}

#
# Shows usage information to user
#
websitemanager-usage() {

    echo -e "${YELLOW}"
    cat <<"USAGE"

Uso: websitemanager [options] <name of vhost>
    -h		|--help   help
    -d          domain of the project eg: site.dev
    -l          list all vhosts
    -t          set vhost template like default. laravel, nodejs
    -pv         set php version vhost
    -dr		custom document root for pointing the domain to existing folder
    -p          sets the application's port for nodejs/proxy
    -u          set domain for the system user like you(anil, vijay, nitin)  
    -install    install the script globally
    -update     Autoupdate script if is needed


USAGE

    echo "Examples:"
    echo
    echo-yellow "Example: for creating a vhost domain \"sitename.dev\" with the template \"wordpress\" and php version 7.2 use below command"
    echo-green "sudo websitemanager -d sitename.dev -t default -f wordpress -pv 7.2  -u {yoursystemusername} #without -pv it will set php8.0 as default php version, if framework -f not defined it will not install it"
    echo-red "Explanation of flags"
    echo-green "-d domainname  // mandatory option"
    echo-green "-pv php version i.e 7.1, 7.2, 8.3"
    echo-green "-dr custom document root of domain i.e /full_path_of_existing_folder, default is /home/{yoursystemusername}/public_html/sites/$domain"
    echo-green "-p port only applicable if -t is node "
    echo-green "-t apache vhost template i.e default, laravel, node "
    echo-green "-f install framework while creating vhost i.e laravel, wordpress"
	

    echo -e "${NC}"
    exit 0

}

#
# install script, instal option to add the script in bin directory
#
websitemanager-install() {
    #websitemanager-verify-sudo;

    if [ ! -e  "$CONFDIR" ]; then
        mkdir "$CONFDIR"
    fi

    #cp template.conf template-phpfpm.conf template-pool.conf $CONFDIR
    cp -r $(pwd)/. $CONFDIR
    ln -s -f $CONFDIR/websitemanager /usr/bin/websitemanager
    ln -s -f $CONFDIR/systemmanager /usr/bin/systemmanager

    echo-green "Script installed! use: sudo systemanager #for packages installation"
    echo-green "Script installed! use: sudo websitemanager # for websites vhosts creation"

    exit 0

}

#
# Update Vhost
#
websitemanager-update() {
    #websitemanager-verify-sudo;
    cd /opt/websitemanager
    git checkout .
    git remote update > /dev/null
    needUpdate=$(git status -uno | grep -c "git pull")

    if [ "$needUpdate" -ne 0 ]; then
        echo-yellow "Need update..."
        git reset --hard origin/master > /dev/null
        echo-green "Update complete!"
        echo-red "Please re-run same command"
        exit 0
    fi
}



#
# List avaliable and enabled vhosts
#
websitemanager-list() {

    echo-yellow "Virtual hosts avaliable:"
    ls -1 "/etc/apache2/sites-available/"

    echo-green "Virtual hosts enabled:"
    ls -1 "/etc/apache2/sites-enabled/"

    exit 0

}



#
# Validate template's existance
#
websitemanager-template() {
    #websitemanager-verify-sudo;
    echo-green "Verifying template..."
        if [ ! -f "/opt/websitemanager/vhosttemplates/$TEMPLATE" ]; then
            echo-red "$TEMPLATE not found!"
            exit 1
        fi
    	if [ $HAS_POOL_TEMPLATE = "1" ]; then
        echo-green "Verifying pool template..."

        if [ ! -f "/opt/websitemanager/phpini-templates/php-fpm.conf" ]; then
                echo-red "$POOL_TEMPLATE not found!"
                exit 1
           
        fi
    fi

}

websitemanager-getusername() {
#websitemanager-verify-sudo;
if [ "$USERNAME" == "" ]; then
    username=$(logname)
else
    username="$USERNAME"
fi
}

#sudoers_user() {
#websitemanager-verify-sudo;
#if ! grep -q "$(logname)" /etc/sudoers; then
#    echo "$(username) ALL = NOPASSWD: /bin/systemctl restart apache2.service, /usr/bin/websitemanager, /usr/bin/systemmanager, /bin/kill" >> /etc/sudoers
#fi
#}

#
# Creates a new vhost in sites available of apache
#
websitemanager-generate-vhost() {
    #websitemanager-verify-sudo;
    echo-green "Creating $DOMAIN virtual host."
    	
    APACHE_CONF="/etc/apache2/sites-available/$DOMAIN.conf"
    cp  $CONFDIR/vhosttemplates/$TEMPLATE $APACHE_CONF
    
    sed -i 's#user#'$username'#g' $APACHE_CONF
    sed -i 's#domain#'$DOMAIN'#g' $APACHE_CONF

   if [ -z "$DOCUMENT_ROOT" ]; then
	    mkdir -p /home/$username/public_html/sites/$DOMAIN/
	    mkdir -p /home/$username/public_html/logs/$DOMAIN
            touch /home/$username/public_html/logs/$DOMAIN/{access.log,error.log}
	    chown -R $username:$username /home/$username/public_html/logs/$DOMAIN
	    chown -R $username:$username /home/$username/public_html/sites/$DOMAIN
    else
	        sed -i "s+/home/$username/public_html/sites/$DOMAIN+$DOCUMENT_ROOT+g" $APACHE_CONF
	    	mkdir -p $DOCUMENT_ROOT
		chown -R $username:$username $DOCUMENT_ROOT
		mkdir -p /home/$username/public_html/logs/$DOMAIN
		touch /home/$username/public_html/logs/$DOMAIN/{access.log,error.log}
		chown -R $username:$username /home/$username/public_html/logs/$DOMAIN
    fi
    	 
    if [ "$TEMPLATE" == "node.conf" ]; then
    sed -i 's#localhost:port#'localhost:$PORT'#g' $APACHE_CONF
    else
    	sed -i 's#php_version#'$PHP_VERSION'#g' $APACHE_CONF
    fi

    if [ $HAS_POOL_TEMPLATE == "1" ];then
        websitemanager-generate-php-pool;
    fi

    if [ ! -f $APACHE_CONF  ]; then
        echo-red "Fail, aborting..."
        exit 1
    fi

}

websitemanager-generate-php-pool() {
    #websitemanager-verify-sudo;
    echo-green "Creating PHP-FPM config for virtual host."
    cp $POOL_TEMPLATE /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
    if [ -z "$DOCUMENT_ROOT" ]; then
    sed -i 's#domain#'$DOMAIN'#g' /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
    else
    sed -i "s+/home/userfpm/public_html/sites/domain+$DOCUMENT_ROOT+g" /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
    sed -i 's#domain#'$DOMAIN'#g' /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
    fi
    sed -i 's#php_version#'$PHP_VERSION'#g' /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
    sed -i 's#userfpm#'$username'#g' /etc/php/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf
}

websitemanager-remove() {
    #websitemanager-verify-sudo;
    FPM_POOL_CONF="/etc/$PHP_VERSION/fpm/pool.d/$CONFNAME"

    echo-yellow "removing domain from /etc/hosts."
    sed -i '/'$DOMAIN'/d' /etc/hosts

    echo-yellow "disabling  $DOMAIN virtual host."
    a2dissite $CONFNAME

    rm "/etc/apache2/sites-available/$CONFNAME"
    service apache2 reload

    if [ -f "$FPM_POOL_CONF" ]; then
        echo-yellow "removing php-fpm associaed with $DOMAIN"
        rm "$FPM_POOL_CONF"
    fi

    exit 0

}

#
#  Adds the new vhost domain in hosts file
#
websitemanager-point-ip() {
    #websitemanager-verify-sudo;
    HOSTS_PATH="/etc/hosts"

    echo-green "pointing $DOMAIN  via /etc/hosts ..."

    if grep -F "$DOMAIN" $HOSTS_PATH
    then
        echo-yellow "Domain already exists"
    else
        sed -i '1s/^/127.0.0.1       '$DOMAIN'\n/' $HOSTS_PATH
    fi

}

websitemanager-ssl-generate() {
cd "$CONFDIR/openssl"
./getcert.sh $DOMAIN >> /dev/null
}
#
# Reloads apache server and php-fpm, if required
#
websitemanager-enable-reload() {
    #websitemanager-verify-sudo;
    a2ensite $DOMAIN

    service apache2 reload

    #echo-green "Virtual host $DOMAIN created you can access via https://$DOMAIN"

    if [ $HAS_POOL_TEMPLATE = "1" ]; then
        service php$PHP_VERSION-fpm restart
        #echo-green "Pool for site with host and pool $CONFNAME enabled"
    fi


}

install_framework(){
echo "document root is $DOCUMENT_ROOT"
if [ -z "$DOCUMENT_ROOT" ]; then
 if [ -z "$(ls -A $DOCUMENT_ROOT)" ]; then
    echo ""
 else
   echo-red "No framework specificed or directory not empty"
   exit 1
 fi
 fi
if [ "$FRAMEWORK" == "laravel" ]; then
    echo-green "================================="
    echo-green "downloading and installing latest Laravel version"
        export COMPOSER_ALLOW_SUPERUSER=1
 	composer create-project laravel/laravel "$DOCUMENT_ROOT"
	chown -R $username:$username $DOCUMENT_ROOT
    temp_DB=${DOMAIN%.*}
    temp_DB=$(sed "s/-/_/g" <<< "$temp_DB")
    DB=${username}_${temp_DB} 
    sudo mysql -e "CREATE DATABASE $DB;"
    sed -i 's/laravel/"$DB"/' $DOCUMENT_ROOT/.env
    sed -i 's/root/"$mysqluser"/' $DOCUMENT_ROOT/.env
    sed -i 's/"DB_PASSWORD="/"DB_PASSWORD=$mysqluserpasswd"/' $DOCUMENT_ROOT/.env
mysqlcred

elif [ "$FRAMEWORK" == "wordpress" ]; then
	cd /tmp
    echo-green "=================================="
	echo-green "downloading and installing wordpress"	
    curl https://wordpress.org/latest.tar.gz -o latest.tar.gz && tar -xzf latest.tar.gz -C "$DOCUMENT_ROOT" --strip-components=1
    
    temp_DB=${DOMAIN%.*}
    temp_DB=$(sed "s/-/_/g" <<< "$temp_DB")
    DB=${username}_${temp_DB} 
    sudo mysql -e "CREATE DATABASE $DB;"
    cp /home/$username/public_html/sites/$DOMAIN/wp-config-sample.php $DOCUMENT_ROOT/wp-config.php
    sed -i 's/database_name_here/"$DB"/' $DOCUMENT_ROOT/wp-config.php
    sed -i 's/username_here/"$mysqluser"/' $DOCUMENT_ROOT/wp-config.php
    sed -i 's/password_here/"$mysqluserpasswd"/' $DOCUMENT_ROOT/wp-config.php
    chown -R $username:$username "$DOCUMENT_ROOT"

mysqlcred
fi
}
function mysqlcred(){
	if [ ! -f ${mysqlcred} ]; then
		echo-green "Setup Mysql account"
		echo-yellow "Please enter mysql username other then root"
	    	read mysqluser
		echo-yellow "Please enter mysql password"
		read mysqluserpasswd
                touch ${mysqlcred} 
                #save mysql credentials in file for further uses
		echo -e "${mysqluser}\n${mysqluserpasswd}" > ${mysqlcred}
	else
	    mysqluser=$(head -n 1 ${mysqlcred})
	    mysqluserpasswd=$(tail -n 1 ${mysqlcred})
fi
}
function savedomainslist(){
	if [ ! -f ${domainslist} ]; then
                touch ${domainslist} 
                #save domains in file for further uses
	elif  [ grep -n "$DOMAIN" ${domainslist} | cut -d: -f1 != "" ];then
               echo -e "${DOMAIN}|${$PHP_VERSION}" > ${domains}
        else 
              sed -i 's/^${DOMAIN}|7.0/test-123.com|${$PHP_VERSION}/g' ${DOMAIN} //need to review part
        fi
}

function setupphpcli(){
if [ ! "$TEMPLATE" == "node.conf" ];then
	echo-green "Setup default php cli version to php$PHP_VERSION"
	update-alternatives --set php /usr/bin/php$PHP_VERSION > /dev/null 2>&1
	echo-yellow "you can use following commond to set default php CLI version via terminal"
	echo-red "sudo update-alternatives --set php /usr/bin/php8.2"
fi
}


verifyuserinput(){
echo-green "=============================================================================="
echo-green
echo-green "Username: $username";
echo-green "Domain: $DOMAIN"
echo-green "VhostTemplate: $TEMPLATE"
if [ -z "$FRAMEWORK"  ]; then
echo-yellow "Framework: Not Defined"
else
echo-green "Framework: $FRAMEWORK"
fi
if [ -z "$DOCUMENT_ROOT" ]; then
#DOCUMENT_ROOT="/home/$username/public_html/sites/$DOMAIN"
echo-green "Document root:/home/$username/public_html/sites/$DOMAIN"
else
    echo-yellow "Custom Document root: $DOCUMENT_ROOT"
fi    
if [ "$TEMPLATE" == 'node.conf' ]; then
    echo-green "Port: $PORT"
else
    echo-green "Php_Version: $PHP_VERSION"
fi


echo-green
echo-green "=============================================================================="
echo-green
echo-red "" 
#read answer
read -p "Would you like to create domain/site with above configuration (y/n)?" answer
case ${answer:0:1} in
    y|Y )
        echo Yes
    ;;
    * )
       exit 1
    ;;
esac
}

#
# Initial script
#
while [ $1 ]; do
    case "$1" in
        '-l') websitemanager-list;;
        '-h'|'--help') websitemanager-usage;;
        '-t') TEMPLATE="$2.conf";;
	'-f') FRAMEWORK="$2";;
        '-pv')
            PHP_VERSION="$2";;
	'-dr') DOCUMENT_ROOT="$2";;    
        '-p') PORT="$2";;    
        '-d') DOMAIN="$2";;
        '-u') USERNAME="$2";;
        '-install') websitemanager-install;;
        '-update') websitemanager-update;;
    esac
    shift
done

#
# Verify the parameters usage
#
if [ "$DOMAIN" == "" ]; then
    echo-red "You need to specify the options -d "
    websitemanager-usage;
    exit 0;
fi

if [ "$PHP_VERSION" == "" ]; then
    PHP_VERSION="8.0"
fi
if [ "$DOCUMENT_ROOT" == "" ]; then
    DOCUMENT_ROOT="/home/$USERNAME/public_html/sites/$DOMAIN"
else
     DOCUMENT_ROOT=$DOCUMENT_ROOT
    

fi

if [ "$FRAMEWORK" == "laravel" ]; then
    TEMPLATE="laravel"
    HAS_POOL_TEMPLATE="1"
elif [ "$FRAMEWORK" == "wordpress" ]; then
    TEMPLATE="wordpress"
    HAS_POOL_TEMPLATE="1"
fi


if [ "$TEMPLATE" == "wordpress" ]; then
    TEMPLATE="default.conf"
    HAS_POOL_TEMPLATE="1"
elif [ "$TEMPLATE" == "node.conf" ]; then
    HAS_POOL_TEMPLATE="0"
elif [ "$TEMPLATE" == "laravel.conf" ]; then
    HAS_POOL_TEMPLATE="1"
fi

if [ "$PORT" == "" ]; then
    PORT="3000"
fi
#
# Do vhost creation process
#
echo-green "$HAS_POOL_TEMPLATE"
websitemanager-update;
#sudoers_user;
websitemanager-getusername;
verifyuserinput;
websitemanager-template;
websitemanager-generate-vhost;
#websitemanager-generate-php-pool;
websitemanager-point-ip;
websitemanager-ssl-generate;
websitemanager-enable-reload;
#mysqlcred;
setupphpcli;
install_framework;
exit 0
